### ISSUE TITLE
Reccurring payment fails

### ISSUE THREAD

**Issue by dpanta94** [woocommerce/woocommerce-gateway-amazon-pay#139]
**Describe the bug**
After update to V2 and make the onboarding, when access to some subscriptions edit page this error appears:

`2021-07-08T12:07:29+00:00 CRITICAL Uncaught Exception: The BillingAgreementId B01-8183465-8846395 is invalid. in /www/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php:428
Stack trace:
#0 /www/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php(369): WC_Gateway_Amazon_Payments_Advanced_Subscriptions_Legacy->handle_generic_api_response_errors('WC_Gateway_Amaz...', Object(SimpleXMLElement), 19349, 'B01-8183465-884...')
#1 /www/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php(817): WC_Gateway_Amazon_Payments_Advanced_Subscriptions_Legacy->get_billing_agreement_details(19349, 'B01-8183465-884...')
#2 /www/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php(733): WC_Gate in /www/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php on line 428`

Looks like a error that pop ups when the billing-agreement is cancelled. Need further invetigation.

**Comment by dpanta94** [comment]
Seems like #136 also fixes that issue. So closing this one too.
