### ISSUE TITLE
Fatal error on updating subscription payment method, subscription switching, etc. due to confusing UI

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-amazon-pay#14]
#### Affected ticket(s)
1970133-zen

#### What I expected
To change subscription payment method to Amazon Pay.

#### What happened instead
On the subscription update page I'm able to select Amazon Pay even when logged out of my Amazon account: 

![Screenshot](https://cld.wthms.co/kEdSlK+)
Screenshot: https://cld.wthms.co/kEdSlK

When I do this and click **Update payment**, I'm seeing a 500 error with no option to progress either way:

```
2019-04-24T09:32:20+00:00 CRITICAL Uncaught Error: Call to a member function validate_fields() on null in /woostore/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-change-payment-gateway.php:391
Stack trace:
#0 /wordpress/core/5.1.1/wp-includes/class-wp-hook.php(286): WC_Subscriptions_Change_Payment_Gateway::change_payment_method_via_pay_shortcode('')
#1 /wordpress/core/5.1.1/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.1.1/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /wordpress/core/5.1.1/wp-settings.php(526): do_action('wp_loaded')
#4 /woostore/wp-config.php(88): require_once('/wordpress/core...')
#5 /wordpress/core/5.1.1/wp-load.php(42): require_once('/woostore/wp-co...')
#6 /wordpress/core/5.1.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#7 /wordpress/core/5.1.1/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in /woostore/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-change-payment-gateway.php on line 391
```

This is because Amazon Pay checkout flow normally doesn't show the payment method radio button and forces the user to login first. Here the radio button is shown, so the user is able to select Amazon Pay without actually connecting to Amazon.

#### Steps to reproduce the issue
1. Enable Amazon Pay for subscriptions,
2. Add a subscription product to cart,
3. Checkout with a different payment method (i.e. Stripe) and complete the order to activate the subscription,
4. Go to My Account > My Subscriptions and open subscription details,
5. Click Change Payment on the subscription page (as described in #339 )
6. Select the Amazon Pay checkbox without logging in to the Amazon account
7. Click **Change payment** and observe the error

Setting high priority - even though that's a corner case it breaks the checkout flow with a fatal and makes terrible UX for the end customers.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dwainm** [comment]
2745412-zen

This is still happening:

Fatal error: Uncaught Error: Call to a member function validate_fields() on null in /home/mpssedb6/test.com/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-change-payment-gateway.php:346 Stack trace:


----

Another chat/ticket where this was causing issues: 2462731-zen
I was able to reproduce the same thing on my test site before I found this issue. So it's still reproducible with these versions:

WooCommerce Amazon Pay Gateway – 1.10.2
WooCommerce Stripe Gateway – 4.3.0
WooCommerce Subscriptions – 2.6.3
WooCommerce – 3.7.1
