### ISSUE TITLE
Bump WP required version and create notification to prevent Fatal errors

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/woocommerce-gateway-amazon-pay#224]
**Describe the bug**
version 2.3.0 of Amazon Pay for WooCommerce is throwing a fatal error if WP version is lower than 5.5

`Fatal error: Uncaught Error: Call to undefined function register_block_type_from_metadata() in /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/blocks/class-wc-amazon-payments-advanced-register-blocks.php:95 Stack trace: #0 /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-includes/class-wp-hook.php(287): WC_Amazon_Payments_Advanced_Register_Blocks->register_amazon_blocks('') #1 /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-settings.php(540): do_action('init') #4 /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-config.php(101): require_once('/srv/users/user...') #5 /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-load.php(37): require_once('/srv/users/user...') #6 /srv/users/user4c0cb805/apps/user4c0cb805/publ in /srv/users/user4c0cb805/apps/user4c0cb805/public/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/blocks/class-wc-amazon-payments-advanced-register-blocks.php on line 95`

**To Reproduce**
1. Any site with WP 5.4.7 version
2. Install and activate Amazon Pay 2.3.0

**Expected behavior**
prevent fatal errors and create a notification that Amazon Pay is compatible with WP 5.8 or higher (like WooCommerce plugin). The fatal error goes away with WP 5.5 or higher

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by alexiglesias31** [comment]
Fixed on #231
